name: Push tag

on:
  push:
    branches:
      - master
    paths:
      - Chart.yaml

jobs:
  cancel-previous:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
  
  push-tag:
    name: Push tag
    runs-on: ubuntu-latest
    needs: [cancel-previous]
    steps:
      - uses: actions/checkout@v2

      - name: Get Chart Version
        id: chart-version
        run: |
          echo "CHART_VERSION=$(grep "version:" Chart.yaml | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          custom_tag: ${{ steps.chart-version.outputs.CHART_VERSION }}
