name: 'Release helm chart'

on:
  push:
    branches:
      - master
    paths:
      - Chart.yaml

jobs:
  cancel-previous:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
  
  push-tag:
    name: Push tag
    runs-on: ubuntu-latest
    needs: [cancel-previous]
    outputs:
      chart-version: ${{ steps.chart-version.outputs.CHART_VERSION }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - uses: actions/checkout@v2

      - name: Get Chart Version
        id: chart-version
        run: |
          echo "CHART_VERSION=$(grep "version:" Chart.yaml | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          custom_tag: ${{ steps.chart-version.outputs.CHART_VERSION }}

  release:
    name: Release helm chart
    runs-on: ubuntu-latest
    needs: [push-tag]

    steps:
      # - name: Build Changelog
      #   id: github_release
      #   uses: mikepenz/release-changelog-builder-action@v3.5.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{  needs.push-tag.outputs.chart-version  }}
          name: Release ${{  needs.push-tag.outputs.chart-version  }}
          body: ${{  needs.push-tag.outputs.changelog  }}
          # body: ${{  steps.github_release.outputs.changelog  }}